### ISSUE TITLE
Enable SASS property typing for nimble-theme-provider variables

### ISSUE THREAD

**Issue by rajsite** [ni/nimble#225]
For applications that use tokens directly we offer nimble-tokens which defines variables.

However, if an application wants to use a theme we currently have themes controlled by a nimble-theme-provider component instance. The component in-turn defines its own set of css custom properties who have values that are changed based on the current theme.

Applications that want to consume tokens that are adjusted for the theme need to use the css custom properties defined at runtime by nimble-theme-provider.

However, this will be brittle. If we refactor / rename variables in nimble-theme-provider there is not a way for consumers to break. ie a property name changes from --generic-font to --label-generic-font will not cause the consuming application to fail to compile if using the css property directly.

One option would be to create a scss/sass file that defines sass variables that are aliased to the variables defined by the nimble-theme-provider.

For example:

```scss
/* nimble-components/design-system-provider-variables.scss*/
$nimble-color: var(--nimble-color);

/*application.scss*/
body {
    background: $nimble-color;
}
```

result:
![image](https://user-images.githubusercontent.com/1588923/145133197-55745ac2-0328-4ccb-ac2d-77f1345fa6fb.png)

Now an application can consume the scss file to define properties and if properties are renamed / removed it will fail build of that application.

Edit1:
An alternative pattern that allows writing to the variable as well. Not sure if we even want that though... should apps be trying to update custom property values directly? The FAST pattern would be to create a new nimble-theme-provider with updated values for that region. Also, code doing [getValueFor](https://github.com/ni/nimble/search?q=getValueFor) of a css property would not see the value of a property edited in this way:

```scss
$nimble-color: --nimble-color;

body {
    background: var($nimble-color);
}

h1 {
    #{$nimble-color}: 'green';
}
```
![image](https://user-images.githubusercontent.com/1588923/145135072-ec5bae3d-3ade-4e6f-9c23-71c302c14944.png)

Edit 2:
We can use a pattern like the following so there is an escape hatch marked internal if you know what you are doing but general users will use the simpler name with the simpler syntax (don't have to surround in `var()`):

```scss
$nimble-color-internal: --nimble-color;
$nimble-color: var($nimble-color-internal);

body {
    background: $nimble-color;
}

h1 {
    #{$nimble-color-internal}: 'green';
}
```

![image](https://user-images.githubusercontent.com/1588923/145135576-89f61913-b385-42bf-b6ff-e8bc8a290539.png)
